sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then cd ./scripts/cron-jobs/dependencies; fi
before_script:
  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then commitlint-travis; fi
  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then yarn generate:man; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then yarn lint:pr; fi
after_success:
  - yarn report-coverage
deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: $GH_TOKEN
    local-dir: src/www
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script:
      - yarn semantic-release
    on:
      branch: master
