sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then cd ./scripts/cron-jobs/dependencies; fi
before_script:
  - commitlint-travis
  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then yarn lint:pr; fi
after_success:
  - yarn report-coverage
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GH_TOKEN
  local-dir: src/www
  on:
    branch: master
