sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then cd ./scripts/cron-jobs/dependencies; fi
  
